[project]
name = "freqtrade0"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "freqtrade",
    "ta-lib>=0.6.3",
]

[tool.uv.sources]
freqtrade = { git = "https://github.com/731315163/freqtrade.git" }


